### ISSUE TITLE
Jump to title Project doesn't work

### ISSUE THREAD

**Issue by bijeshsingha** [judygab/web-dev-projects#16]
![image](https://user-images.githubusercontent.com/58762636/194011550-a0305e72-9ada-4b52-9777-9f2ff0ab7325.png)
Nav bar Project

**Comment by Pedrenri** [comment]
Check if your NavBar link looks like this and if there is anything in the Banner.js with an ID of 'home'
![image](https://user-images.githubusercontent.com/99422315/194191247-79c207d6-76dc-4eaf-b519-fd76a624fc94.png)
