### ISSUE TITLE
want hover effect.

### ISSUE THREAD

**Issue by swaidniazi1** [judygab/web-dev-projects#4]
Hello!! 
how r u Miss!
can we add hover {
cursor : pointer;
} effect for the three tabs under projects. when, i move cursor on tabs it becomes reading one.
so how to add effect, please tell.

**Comment by ItsAndrea** [comment]
Hi, to add that effect you have to do a contribution and wait for the approval. 

**Steps**

- Fork this repository
- Clone the repository
- Create a branch
- Make necessary changes and commit those changes
- Push changes to GitHub
- Submit your changes for review

Find the full step by step here ===> https://github.com/ItsAndrea/first-contributions

If this helped, please close the issue :)
